version: '3'
services:
  blob:
    image: minio/minio
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
  db:
    image: mysql:5.7
    volumes:
      - ./init.sql:/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  server:
    build: .
    environment:
      - MYSQL_ADDR=db
      - MYSQL_PORT=3306
      - MINIO_ENDPOINT=blob:9000

      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
  loadbalancer:
    image: dockercloud/haproxy
    links:
     - server
    ports:
     - '80:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
